<script setup lang="ts">
import { provide } from 'vue'
import type { PopularBuild } from './types'

// Example popular builds data - you can replace this with your actual data
const popularBuilds: PopularBuild[] = [
  // Add your popular builds here as an array
  // Example:
  {
    id: '1',
    title: 'Maelle Nuke',
    description: 'Burn stacking build for Maelle',
    author: 'Tenkiei',
    encodedBuild: 'eyJscyI6IjU0LDIwNiwxNTUsMjEsMTIwLDExMSwxMCwzOCwxNDgsMTI1LDE0NywxMDUsMjAwLDE5OSwxNDYsMjA4LDIxNCwxOTYsMTg2LDEyMyw2OCw3MCwxNSwxOCwxNiwxMzIiLCJwcyI6IjYwLDE2OCwxMzMiLCJjaCI6Miwic2siOiIxMCwzNCw5LDI2LDMzLDE1IiwiYyI6IlVzZSBNZWRhbHVtIHdlYXBvbi5cbkF0dHJpYnV0ZXM6IG1heCBkZWZlbnNlLCB0aGVuIGFnaWxpdHksIHRoZW4gbWlnaHQuXG5cbk51a2UgZW5lbWllcyB3aXRoIEJ1cm5pbmcgQ2FudmFzIGFmdGVyIHN0YWNraW5nIGEgbG90IG9mIGJ1cm5zIG9uIHRoZW0sIG9yIGRvIEZsZXVyZXQgRnVyeSB0byBkb3VibGUgdGhlaXIgYnVybi4iLCJ0IjoiTWFlbGxlIG51a2UifQ==',
    tags: ['DPS', 'Burn'],
    source: 'https://maxroll.gg/clair-obscur-expedition-33/planner?profile=qr1j4009',
    createdAt: '2024-05-08'
  },
  {
    id: '2',
    title: 'Verso Burn',
    description: 'Burn stacking build for Verso',
    author: 'Tenkiei',
    encodedBuild: 'eyJscyI6IjU3LDU2LDE1NSwxMjAsNjEsNzYsMTExLDQwLDE4MiwxMTYsMTMxLDc4LDE5NCw0MiwxNTYsMTQ3LDE0LDEzLDIxNSwzNiw3MCwyMDMsMjA2LDE5NiwzOCwxMjUsMTQ4LDYwLDE2OCwyMDgsMTYwLDIxNCw2OCIsInBzIjoiNTQsMTIzLDU4IiwiY2giOjYsInNrIjoiMTQ0LDE1MyIsInQiOiJWZXJzbyBCdXJuIn0=',
    tags: ['DPS', 'Burn'],
    source: 'https://maxroll.gg/clair-obscur-expedition-33/planner?profile=qr1j4009',
    createdAt: '2024-05-08'
  },
  {
    id: '3',
    title: 'Lune Dark Stain',
    description: 'Scaverim build for Lune',
    author: 'Fohan',
    encodedBuild: 'eyJscyI6IjE0Niw1OSw2MywxMTEsMTEwLDEwNSw5Nyw5Niw4OSw5MSwxMDYsMTAwLDk5LDEwMiwxMDQsMjA2LDIxLDEwLDM0LDcxLDE5NCw0MiwxNjksMTU2LDE3NywxLDE0LDE5NywxNywxNSwzOCwxNDgsMTU1LDE4MiwyMDUsMTI1LDIxNCwxMzIsNjAsMTg0LDIwOSw4NywxMTgsNjIsMTI3LDEzMSwzMSwzMCwyNCwxOSw3OCw1NCwxMzMsMjA0LDE1NCwxNjMsNDAsNDcsNDgsMTI0LDQ1LDQ0LDUxLDQxLDQ5LDgyLDEyMywxMTcsMTUzLDE1MSw3MywxODYsMTgxIiwiY2giOjQsInNrIjoiNjMsODUsNjcsNjYsNzMsNzQiLCJjIjoiaHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1FaE51cS13RDhWMFxuXG5Vc2UgU2NhdmVyaW0gd2VhcG9uLlxuXG5UaGlzIGlzIHRoZSBwb3RlbnRpYWwgb2YgYSBEYXJrIHN0YWluIGJ1aWxkLiBXYW50ZWQgdG8gZXhwZXJpbWVudCB3aXRoIGl0IGFuZCB3YXMgaGFwcHkgd2l0aCBpdCBvdmVyYWxsIG9uIGhvdyBpdCBmZWx0LiBOb3cgSSB3YW50IHRvIHNoYXJlIHdpdGggeW91IVxuXG5JdCBjcmVhdGVzIHN1Y2ggdW5pcXVlIGFuZCBkeW5hbWljIGdhbWVwbGF5LiBTbyB3aGF0IGJldHRlciB3YXkgdG8gdGVzdCBpdCB2cyBhIHN1cGVyYm9zcyBzb2xvISAoZm9yIHRoZSBtb3N0IHBhcnQpXG5cblxuV2hpbGUgSSBwdXQgc29tZSBpbmZvIGluIHRoZSBkZXNjcmlwdGlvbiB2aWEgeW91dHViZSBJJ2xsIGV4cGxhaW4gbXkgdGhvdWdodCBwcm9jZXNzIGhlcmUuIFxuXG5cblNvIHRoZSByZWFzb24gd2h5IEkgcHJlZmVyIExpZ2h0aW5nIGRhbmNlIG92ZXIgZWxlbWVudGFsIGdlbmVzaXMgd2FzIGJlY2F1c2UgaXQgYWx3YXlzIGRpZCBzbGlnaHRseSBtb3JlIGRhbWFnZSAoMSB0byAybSBnaXZlIG9yIHRha2UpIGJ1dCB0aGUgbW9zdCBpbXBvcnRhbnQgZmFjdG9yIGhlcmUgd2FzIGlmIEkgd2VyZSB0byBjb25zdW1lIGVsZW1lbnRhbCBnZW5lc2lzIHN0YWlucyBhbmQgaXQgZG9lc24ndCBwcm9jIGEgZGFyayBzdGFpbiB0aGVuIHlvdSdyZSBmb3JjZWQgYmFjayB0byBlbGVtZW50YWwgdHJpY2tzLiBJJ2Qgb25seSB1c2UgZWxlbWVudGFsIGdlbmVzaXMgdmlhIG11bHRpdGFyZ2V0IGJvc3Nlcy9lbmVtaWVzLiBUaGF0IHdheSB5b3VyIG92ZXJhbGwgZGFtYWdlIG91dHB1dCBwZXIgdHVybiBpcyBjb25zaXN0ZW50IGFuZCBncmVhdGVyLiBcblxuXG5OZXh0IGFzIHlvdXIgZGFyayBzdGFpbnMgc3RhcnQgYnVpbGRpbmcgdXAgc3BlY2lmaWNhbGx5IGFyb3VuZCB0aGUgMiBzdGFpbiBtYXJrIHlvdSdyZSBsZWZ0IHdpdGggYSBmZXdlciBvcHRpb25zIHlvdSdsbCBtYW5hZ2UgZmluZSBpZiB5b3Ugcm90YXRlIGJldHdlZW4gY3J1c3RhbCBjcnVzaCBhbmQgdHlwaG9vbi4gSWYgYnkgdGhlIGVuZCB0eXBob29uIGRvZXNuJ3QgZ2l2ZSB5b3UgYSAzcmQgZGFya3N0YWluLCB1c2UgR0EgbHZsIDEgdHJlbW9yIGFuZCByaW5zZSBhbmQgcmVwZWF0IHVudGlsIHlvdSBnZXQgZGFyayBzdGFpbnMuXG5cblxuSSdkIGxpa2UgdG8gYWRkIGluIGJlY2F1c2UgeW91J3JlIGFsc28gbWl4aW5nIHR5cGhvb24geW91J3JlIGFibGUgdG8gdXNlIHBsZW50eSBvZiBzdXBwb3J0IHBpY3RvIGJ1ZmZpbmcgZHVlIHRvIHRoZSBoZWFsaW5nLiAoSSBkb24ndCBmb3IgdGhlIHZpZGVvIGJlY2F1c2UgSSBuZWVkIHRvIGRvIGFzIG11Y2ggZGFtYWdlIGFzIHBvc3NpYmxlKSBMYXN0bHkgeW91IGNhbiBnZXQgYW55IHN0YWluIGNvbG9yIGZvciB0aGUgNHRoIGNvbnN1bWUgYXR0ZW1wdCBhbmQgdHJ5IHRvIHVzZSBtYXloZW0uIElmIHlvdSBkb24ndCBnZXQgYSA0dGggZGFyayBzdGFpbiAtPiBiZSBzYWQuIFJpbnNlIGFuZCByZXBlYXQgdW50aWwgNHRoIGRhcmsgc3RhaW4uIFRoZW4gZm9sbG93IGl0IHVwIHdpdGggYSBzcGVsbCBvZiB5b3VyIGNob29zaW5nLiBcblxuXG5Ib3dldmVyIGtlZXAgaW4gbWluZCB3aXRoIDMgZGFyayBzdGFpbnMgYW5kIGEgbGlnaHQgc3RhaW4gYSBHQSBsdmwgMyB3aWxsIHN0aWxsIGRvIGluY3JlZGlibGUgZGFtYWdlLlxuXG5cbkdvdCBhcm91bmQgdG8gZWRpdGluZyB0aGUgcGljdG9zIGFuZCBidXQgdW5mb3J0dW5hdGVseSB5ZXMgaXQncyBleHRyZW1lbHkgbHVtaW5hIGhlYXZ5IGR1ZSB0byBob3cgaGVhdnkgdGhlIEFQIHVzYWdlIGlzIGZvciB0aGlzIGJ1aWxkLiBUcnkgZXhwbG9yaW5nIGFuZCBwbGF5aW5nIGFyb3VuZCA0MDAtNTAwIHJhbmdlIGFuZCB5b3Ugc2hvdWxkIHN0aWxsIGRvIGFtYXppbmcgb3V0cHV0LlxuXG5cblBvdGVudGlhbCBvZiBkYW1hZ2Ugd2l0aCA0IGRhcmtzdGFpbnMgdnMgdGhlIHN1cGVyYm9zcyBidXQgZGlkbid0IGhhcHBlbiB0byByZWNvcmQuIiwidCI6Ikx1bmUgRGFyayBTdGFpbiJ9',
    tags: ['DPS'],
    source: 'https://maxroll.gg/clair-obscur-expedition-33/planner?profile=1mdgb0jr',
    createdAt: '2024-05-19'
  }
]

// Provide popular builds to child components
provide('popularBuilds', popularBuilds)
</script>

<template>
  <router-view />
</template>